#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "  🚀 AI Task Board - Manual Start Commands"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📍 Navigate to the project directory:"
echo "   cd /Users/admin/Documents/Thomas-SRC/KabanAI/ai-board"
echo ""
echo "🔧 Activate the virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "▶️  Start the server:"
echo "   cd backend"
echo "   python3 app.py"
echo ""
echo "🌐 Open in browser:"
echo "   http://localhost:5001"
echo ""
echo "⏹️  To stop the server:"
echo "   Press CTRL+C in the terminal"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🎯 ONE-LINE COMMAND (copy and paste):"
echo ""
echo "cd /Users/admin/Documents/Thomas-SRC/KabanAI/ai-board && source venv/bin/activate && cd backend && python3 app.py"
echo ""
echo "════════════════════════════════════════════════════════════"
