#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         🤖 AI Task Board - Quick Start Guide              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Application is running at:"
echo "   http://localhost:5001"
echo ""
echo "📋 Features:"
echo "   • Create projects and organize tasks in Kanban lanes"
echo "   • Execute AI CLI commands (gh copilot, gemini, etc.)"
echo "   • Parallel execution for tasks with same order"
echo "   • Real-time status monitoring"
echo "   • Git repository integration"
echo "   • Remote SSH execution support"
echo ""
echo "🎨 Task Status Colors:"
echo "   Purple  - Pending (not started)"
echo "   Green   - Running (in progress)"
echo "   Blue    - Success (completed)"
echo "   Red     - Error (failed)"
echo ""
echo "🚀 Quick Start:"
echo "   1. Open http://localhost:5001 in your browser"
echo "   2. Click 'New Project' to create your first project"
echo "   3. Add tasks to any lane (Architecture, Documentation, etc.)"
echo "   4. Set execution order (same number = parallel execution)"
echo "   5. Click 'Run Project' to start execution"
echo ""
echo "📁 Project Structure:"
echo "   • Database: data/aiboard.db"
echo "   • Working dirs: data/workdirs/"
echo "   • Backend: Flask REST API (Python)"
echo "   • Frontend: Vanilla JS + CSS"
echo ""
echo "⚠️  To stop the server, press CTRL+C"
echo ""
